In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
career_stats = pd.read_csv("data/career_fighter_stats.csv")
career_stats

,Unnamed: 0,name,ufc_record,nickname,height,reach,weight,stance,DOB,SLpM,SApM,Str_Acc_pct,Str_Def_pct,TD_Avg,TD_Acc_pct,TD_Def_pct,Sub_Avg
0,0,Tom Aaron,5-3-0,NaN,--,--,155,NaN,"Jul 13, 1978",0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
1,1,Danny Abbadi,4-6-0,THE ASSASSIN,"5' 11""",--,155,Orthodox,"Jul 03, 1983",3.29,4.41,38.0,57.0,0.00,0.0,77.0,0.0
2,2,David Abbott,10-15-0,TANK,"6' 0""",--,265,Switch,--,1.35,3.55,30.0,38.0,1.07,33.0,66.0,0.0
3,3,Shamil Abdurakhimov,20-5-0,ABREK,"6' 3""","76""",235,Orthodox,"Sep 02, 1981",2.45,2.45,44.0,58.0,1.23,24.0,47.0,0.2
4,4,Hiroyuki Abe,8-15-3 (1 NC),ABE ANI,"5' 6""",--,145,Orthodox,--,1.71,3.11,36.0,63.0,0.00,0.0,33.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3655,3655,Dave Zitanick,5-7-0 (1 NC),NaN,--,--,170,NaN,"Mar 05, 1980",0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
3656,3656,Alex Zuniga,6-3-0,NaN,--,--,145,NaN,--,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
3657,3657,George Zuniga,3-1-0,NaN,"5' 9""",--,185,NaN,--,7.64,5.45,38.0,37.0,0.00,0.0,100.0,0.0
3658,3658,Allan Zuniga,13-1-0,TIGRE,"5' 7""","70""",155,Orthodox,"Apr 04, 1992",3.93,1.80,52.0,61.0,0.00,0.0,57.0,1.0
3659,3659,Virgil Zwicker,15-6-1,REZDOG,"6' 2""","74""",205,NaN,"Jun 26, 1982",3.34,4.87,48.0,39.0,1.31,30.0,50.0,0.0

In [3]:
career_stats = career_stats.drop(columns=["nickname", "Unnamed: 0"])
# career_stats = career_stats[career_stats["height"].str.contains("-")==False]
# career_stats = career_stats[career_stats["weight"].str.contains("-")==False]
# career_stats = career_stats[career_stats["DOB"].str.contains("-")==False]
career_stats

,name,ufc_record,height,reach,weight,stance,DOB,SLpM,SApM,Str_Acc_pct,Str_Def_pct,TD_Avg,TD_Acc_pct,TD_Def_pct,Sub_Avg
0,Tom Aaron,5-3-0,--,--,155,NaN,"Jul 13, 1978",0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
1,Danny Abbadi,4-6-0,"5' 11""",--,155,Orthodox,"Jul 03, 1983",3.29,4.41,38.0,57.0,0.00,0.0,77.0,0.0
2,David Abbott,10-15-0,"6' 0""",--,265,Switch,--,1.35,3.55,30.0,38.0,1.07,33.0,66.0,0.0
3,Shamil Abdurakhimov,20-5-0,"6' 3""","76""",235,Orthodox,"Sep 02, 1981",2.45,2.45,44.0,58.0,1.23,24.0,47.0,0.2
4,Hiroyuki Abe,8-15-3 (1 NC),"5' 6""",--,145,Orthodox,--,1.71,3.11,36.0,63.0,0.00,0.0,33.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3655,Dave Zitanick,5-7-0 (1 NC),--,--,170,NaN,"Mar 05, 1980",0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
3656,Alex Zuniga,6-3-0,--,--,145,NaN,--,0.00,0.00,0.0,0.0,0.00,0.0,0.0,0.0
3657,George Zuniga,3-1-0,"5' 9""",--,185,NaN,--,7.64,5.45,38.0,37.0,0.00,0.0,100.0,0.0
3658,Allan Zuniga,13-1-0,"5' 7""","70""",155,Orthodox,"Apr 04, 1992",3.93,1.80,52.0,61.0,0.00,0.0,57.0,1.0
3659,Virgil Zwicker,15-6-1,"6' 2""","74""",205,NaN,"Jun 26, 1982",3.34,4.87,48.0,39.0,1.31,30.0,50.0,0.0

In [4]:
fighter_info = career_stats[["name", "DOB", "ufc_record", "height", "weight", "reach", "stance"]]
fighter_info

,name,DOB,ufc_record,height,weight,reach,stance
0,Tom Aaron,"Jul 13, 1978",5-3-0,--,155,--,NaN
1,Danny Abbadi,"Jul 03, 1983",4-6-0,"5' 11""",155,--,Orthodox
2,David Abbott,--,10-15-0,"6' 0""",265,--,Switch
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,"6' 3""",235,"76""",Orthodox
4,Hiroyuki Abe,--,8-15-3 (1 NC),"5' 6""",145,--,Orthodox
...,...,...,...,...,...,...,...
3655,Dave Zitanick,"Mar 05, 1980",5-7-0 (1 NC),--,170,--,NaN
3656,Alex Zuniga,--,6-3-0,--,145,--,NaN
3657,George Zuniga,--,3-1-0,"5' 9""",185,--,NaN
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,"5' 7""",155,"70""",Orthodox
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,"6' 2""",205,"74""",NaN

In [5]:
no_height = fighter_info[fighter_info["height"].str.contains("-")]
no_height

,name,DOB,ufc_record,height,weight,reach,stance
0,Tom Aaron,"Jul 13, 1978",5-3-0,--,155,--,NaN
35,Brett Albee,--,3-2-0,--,225,--,NaN
40,Israel Albuquerque,--,0-3-0,--,185,--,Orthodox
41,Juan Alcain,--,1-2-0,--,--,--,NaN
57,Levi Alford,--,1-7-0,--,--,--,NaN
...,...,...,...,...,...,...,...
3619,Artenus Young,"Jul 16, 1980",10-12-0,--,205,--,NaN
3632,Joao Zaiden,"Mar 16, 1993",10-3-0,--,205,--,NaN
3650,Mike Zichelle,--,8-4-0,--,205,--,NaN
3655,Dave Zitanick,"Mar 05, 1980",5-7-0 (1 NC),--,170,--,NaN
3656,Alex Zuniga,--,6-3-0,--,145,--,NaN

In [6]:
fighter_info = fighter_info[~fighter_info["height"].str.contains("-")]
fighter_info

,name,DOB,ufc_record,height,weight,reach,stance
1,Danny Abbadi,"Jul 03, 1983",4-6-0,"5' 11""",155,--,Orthodox
2,David Abbott,--,10-15-0,"6' 0""",265,--,Switch
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,"6' 3""",235,"76""",Orthodox
4,Hiroyuki Abe,--,8-15-3 (1 NC),"5' 6""",145,--,Orthodox
5,Daichi Abe,"Nov 27, 1991",6-2-0,"5' 11""",170,"71""",Orthodox
...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,"5' 6""",145,"68""",Southpaw
3654,Igor Zinoviev,--,4-1-2,"6' 1""",199,--,Orthodox
3657,George Zuniga,--,3-1-0,"5' 9""",185,--,NaN
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,"5' 7""",155,"70""",Orthodox
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,"6' 2""",205,"74""",NaN

In [7]:
fighter_info[["height_feet", "height_inches"]] = fighter_info.height.str.split("'", expand=True)
fighter_info

/home/audricperger/anaconda3/envs/pyenv/lib/python3.8/site-packages/pandas/core/frame.py:3191: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,name,DOB,ufc_record,height,weight,reach,stance,height_feet,height_inches
1,Danny Abbadi,"Jul 03, 1983",4-6-0,"5' 11""",155,--,Orthodox,5,"11"""
2,David Abbott,--,10-15-0,"6' 0""",265,--,Switch,6,"0"""
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,"6' 3""",235,"76""",Orthodox,6,"3"""
4,Hiroyuki Abe,--,8-15-3 (1 NC),"5' 6""",145,--,Orthodox,5,"6"""
5,Daichi Abe,"Nov 27, 1991",6-2-0,"5' 11""",170,"71""",Orthodox,5,"11"""
...,...,...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,"5' 6""",145,"68""",Southpaw,5,"6"""
3654,Igor Zinoviev,--,4-1-2,"6' 1""",199,--,Orthodox,6,"1"""
3657,George Zuniga,--,3-1-0,"5' 9""",185,--,NaN,5,"9"""
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,"5' 7""",155,"70""",Orthodox,5,"7"""
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,"6' 2""",205,"74""",NaN,6,"2"""

In [8]:
fighter_info["height_inches"] = fighter_info["height_inches"].str.strip('"')
fighter_info["height_feet"] = fighter_info["height_feet"].astype(int)
fighter_info["height_inches"] = fighter_info["height_inches"].astype(int)
fighter_info

<ipython-input-8-c2b6ab198ea2>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fighter_info["height_inches"] = fighter_info["height_inches"].str.strip('"')
<ipython-input-8-c2b6ab198ea2>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fighter_info["height_feet"] = fighter_info["height_feet"].astype(int)
<ipython-input-8-c2b6ab198ea2>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fighter_info["height_inches"] = fighter_info["height_inches"].astype(int)

,name,DOB,ufc_record,height,weight,reach,stance,height_feet,height_inches
1,Danny Abbadi,"Jul 03, 1983",4-6-0,"5' 11""",155,--,Orthodox,5,11
2,David Abbott,--,10-15-0,"6' 0""",265,--,Switch,6,0
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,"6' 3""",235,"76""",Orthodox,6,3
4,Hiroyuki Abe,--,8-15-3 (1 NC),"5' 6""",145,--,Orthodox,5,6
5,Daichi Abe,"Nov 27, 1991",6-2-0,"5' 11""",170,"71""",Orthodox,5,11
...,...,...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,"5' 6""",145,"68""",Southpaw,5,6
3654,Igor Zinoviev,--,4-1-2,"6' 1""",199,--,Orthodox,6,1
3657,George Zuniga,--,3-1-0,"5' 9""",185,--,NaN,5,9
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,"5' 7""",155,"70""",Orthodox,5,7
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,"6' 2""",205,"74""",NaN,6,2

In [9]:
fighter_info["height_in"] = (fighter_info["height_feet"] * 12) + fighter_info["height_inches"]
fighter_info

<ipython-input-9-2b0962619a41>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fighter_info["height_in"] = (fighter_info["height_feet"] * 12) + fighter_info["height_inches"]

,name,DOB,ufc_record,height,weight,reach,stance,height_feet,height_inches,height_in
1,Danny Abbadi,"Jul 03, 1983",4-6-0,"5' 11""",155,--,Orthodox,5,11,71
2,David Abbott,--,10-15-0,"6' 0""",265,--,Switch,6,0,72
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,"6' 3""",235,"76""",Orthodox,6,3,75
4,Hiroyuki Abe,--,8-15-3 (1 NC),"5' 6""",145,--,Orthodox,5,6,66
5,Daichi Abe,"Nov 27, 1991",6-2-0,"5' 11""",170,"71""",Orthodox,5,11,71
...,...,...,...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,"5' 6""",145,"68""",Southpaw,5,6,66
3654,Igor Zinoviev,--,4-1-2,"6' 1""",199,--,Orthodox,6,1,73
3657,George Zuniga,--,3-1-0,"5' 9""",185,--,NaN,5,9,69
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,"5' 7""",155,"70""",Orthodox,5,7,67
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,"6' 2""",205,"74""",NaN,6,2,74

In [10]:
fighter_info = fighter_info.drop(columns=["height", "height_feet", "height_inches"])
fighter_info

,name,DOB,ufc_record,weight,reach,stance,height_in
1,Danny Abbadi,"Jul 03, 1983",4-6-0,155,--,Orthodox,71
2,David Abbott,--,10-15-0,265,--,Switch,72
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,"76""",Orthodox,75
4,Hiroyuki Abe,--,8-15-3 (1 NC),145,--,Orthodox,66
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,"71""",Orthodox,71
...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,145,"68""",Southpaw,66
3654,Igor Zinoviev,--,4-1-2,199,--,Orthodox,73
3657,George Zuniga,--,3-1-0,185,--,NaN,69
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,155,"70""",Orthodox,67
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,205,"74""",NaN,74

In [11]:
fighter_info["reach"] = fighter_info["reach"].str.strip('"')
fighter_info

,name,DOB,ufc_record,weight,reach,stance,height_in
1,Danny Abbadi,"Jul 03, 1983",4-6-0,155,--,Orthodox,71
2,David Abbott,--,10-15-0,265,--,Switch,72
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,76,Orthodox,75
4,Hiroyuki Abe,--,8-15-3 (1 NC),145,--,Orthodox,66
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,71,Orthodox,71
...,...,...,...,...,...,...,...
3653,Cat Zingano,"Jul 01, 1982",10-4-0,145,68,Southpaw,66
3654,Igor Zinoviev,--,4-1-2,199,--,Orthodox,73
3657,George Zuniga,--,3-1-0,185,--,NaN,69
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,155,70,Orthodox,67
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,205,74,NaN,74

In [12]:
no_reach = fighter_info[fighter_info["reach"].str.contains("-")]
no_reach

,name,DOB,ufc_record,weight,reach,stance,height_in
1,Danny Abbadi,"Jul 03, 1983",4-6-0,155,--,Orthodox,71
2,David Abbott,--,10-15-0,265,--,Switch,72
4,Hiroyuki Abe,--,8-15-3 (1 NC),145,--,Orthodox,66
6,Papy Abedi,"Jun 30, 1978",10-4-0,185,--,Southpaw,71
7,Ricardo Abreu,"Apr 27, 1984",5-1-0,185,--,Orthodox,71
...,...,...,...,...,...,...,...
3643,Carlos Zevallos,--,3-4-0,205,--,Orthodox,72
3651,James Zikic,"Mar 01, 1977",21-10-2,205,--,Orthodox,74
3652,Errol Zimmerman,"Apr 20, 1986",0-1-0,185,--,Orthodox,75
3654,Igor Zinoviev,--,4-1-2,199,--,Orthodox,73
3657,George Zuniga,--,3-1-0,185,--,NaN,69

In [13]:
reach = fighter_info[~fighter_info["reach"].str.contains("-")]
reach

,name,DOB,ufc_record,weight,reach,stance,height_in
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,76,Orthodox,75
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,71,Orthodox,71
8,Klidson Abreu,"Dec 24, 1992",15-4-0 (1 NC),205,74,Orthodox,72
11,Juan Adams,"Jan 16, 1992",5-3-0,265,80,Orthodox,77
12,Anthony Adams,"Jan 13, 1988",8-2-0,185,76,Orthodox,73
...,...,...,...,...,...,...,...
3648,Zhalgas Zhumagulov,"Aug 29, 1988",13-5-0,125,66,Switch,64
3649,Fares Ziam,"Mar 21, 1997",11-3-0,155,75,Orthodox,73
3653,Cat Zingano,"Jul 01, 1982",10-4-0,145,68,Southpaw,66
3658,Allan Zuniga,"Apr 04, 1992",13-1-0,155,70,Orthodox,67
3659,Virgil Zwicker,"Jun 26, 1982",15-6-1,205,74,NaN,74

In [14]:
no_reach["reach"] = no_reach["height_in"]
no_reach

<ipython-input-14-222864b2826e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  no_reach["reach"] = no_reach["height_in"]

,name,DOB,ufc_record,weight,reach,stance,height_in
1,Danny Abbadi,"Jul 03, 1983",4-6-0,155,71,Orthodox,71
2,David Abbott,--,10-15-0,265,72,Switch,72
4,Hiroyuki Abe,--,8-15-3 (1 NC),145,66,Orthodox,66
6,Papy Abedi,"Jun 30, 1978",10-4-0,185,71,Southpaw,71
7,Ricardo Abreu,"Apr 27, 1984",5-1-0,185,71,Orthodox,71
...,...,...,...,...,...,...,...
3643,Carlos Zevallos,--,3-4-0,205,72,Orthodox,72
3651,James Zikic,"Mar 01, 1977",21-10-2,205,74,Orthodox,74
3652,Errol Zimmerman,"Apr 20, 1986",0-1-0,185,75,Orthodox,75
3654,Igor Zinoviev,--,4-1-2,199,73,Orthodox,73
3657,George Zuniga,--,3-1-0,185,69,NaN,69

In [15]:
frames = [reach, no_reach]
fighter_df = pd.concat(frames)
fighter_df

,name,DOB,ufc_record,weight,reach,stance,height_in
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,76,Orthodox,75
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,71,Orthodox,71
8,Klidson Abreu,"Dec 24, 1992",15-4-0 (1 NC),205,74,Orthodox,72
11,Juan Adams,"Jan 16, 1992",5-3-0,265,80,Orthodox,77
12,Anthony Adams,"Jan 13, 1988",8-2-0,185,76,Orthodox,73
...,...,...,...,...,...,...,...
3643,Carlos Zevallos,--,3-4-0,205,72,Orthodox,72
3651,James Zikic,"Mar 01, 1977",21-10-2,205,74,Orthodox,74
3652,Errol Zimmerman,"Apr 20, 1986",0-1-0,185,75,Orthodox,75
3654,Igor Zinoviev,--,4-1-2,199,73,Orthodox,73
3657,George Zuniga,--,3-1-0,185,69,NaN,69

In [16]:
fighter_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3392 entries, 3 to 3657
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3392 non-null   object
 1   DOB         3392 non-null   object
 2   ufc_record  3392 non-null   object
 3   weight      3392 non-null   object
 4   reach       3392 non-null   object
 5   stance      2777 non-null   object
 6   height_in   3392 non-null   int64
dtypes: int64(1), object(6)
memory usage: 212.0+ KB

In [17]:
fighter_df["reach"] = fighter_df["reach"].astype(int)
fighter_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3392 entries, 3 to 3657
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        3392 non-null   object
 1   DOB         3392 non-null   object
 2   ufc_record  3392 non-null   object
 3   weight      3392 non-null   object
 4   reach       3392 non-null   int64
 5   stance      2777 non-null   object
 6   height_in   3392 non-null   int64
dtypes: int64(2), object(5)
memory usage: 212.0+ KB

In [18]:
fighter_df["stance"].value_counts()

 Orthodox       2150
 Southpaw        491
 Switch          126
 Open Stance       7
 Sideways          3
Name: stance, dtype: int64

In [19]:
fighter_df["stance"] = fighter_df["stance"].astype(str)

In [20]:
fighter_df["stance"] = fighter_df["stance"].replace({"nan" : "Orthodox"})
fighter_df["stance"] = fighter_df["stance"].replace({" Orthodox" : "Orthodox"})
fighter_df["stance"] = fighter_df["stance"].replace({" Southpaw" : "Southpaw"})
fighter_df["stance"] = fighter_df["stance"].replace({" Switch" : "Switch"})
fighter_df["stance"] = fighter_df["stance"].replace({" Open Stance" : "Switch"})
fighter_df["stance"] = fighter_df["stance"].replace({" Sideways" : "Switch"})
fighter_df["stance"].value_counts()

Orthodox    2765
Southpaw     491
Switch       136
Name: stance, dtype: int64

In [21]:
fighter_df["weight"].value_counts()

170    531
155    489
185    427
145    382
135    339
      ...
219      1
410      1
239      1
234      1
330      1
Name: weight, Length: 111, dtype: int64

In [22]:
fighter_df["weight"].isna().sum()

0

In [23]:
fighter_df

,name,DOB,ufc_record,weight,reach,stance,height_in
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,76,Orthodox,75
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,71,Orthodox,71
8,Klidson Abreu,"Dec 24, 1992",15-4-0 (1 NC),205,74,Orthodox,72
11,Juan Adams,"Jan 16, 1992",5-3-0,265,80,Orthodox,77
12,Anthony Adams,"Jan 13, 1988",8-2-0,185,76,Orthodox,73
...,...,...,...,...,...,...,...
3643,Carlos Zevallos,--,3-4-0,205,72,Orthodox,72
3651,James Zikic,"Mar 01, 1977",21-10-2,205,74,Orthodox,74
3652,Errol Zimmerman,"Apr 20, 1986",0-1-0,185,75,Orthodox,75
3654,Igor Zinoviev,--,4-1-2,199,73,Orthodox,73
3657,George Zuniga,--,3-1-0,185,69,Orthodox,69

In [24]:
no_dob = fighter_df[fighter_df["DOB"].str.contains("-")]
no_dob

                  name  DOB      ufc_record weight  reach    stance  height_in
889         Per Eklund   --          14-5-1    155     72  Orthodox         70
1852      Jess Liaudin   --         20-11-0    170     72  Orthodox         69
3487    Curt Warburton   --          13-6-0    155     73  Orthodox         72
2         David Abbott   --         10-15-0    265     72    Switch         72
4         Hiroyuki Abe   --   8-15-3 (1 NC)    145     66  Orthodox         66
...                ...  ...             ...    ...    ...       ...        ...
3625       Han Ten Yun   --           0-1-0    220     71  Orthodox         71
3640  Daniel Zellhuber   --          10-0-0    155     73  Orthodox         73
3643   Carlos Zevallos   --           3-4-0    205     72  Orthodox         72
3654     Igor Zinoviev   --           4-1-2    199     73  Orthodox         73
3657     George Zuniga   --           3-1-0    185     69  Orthodox         69

[541 rows x 7 columns]

In [ ]:
clean_fighter_df = fighter_df[~fighter_df["DOB"].str.contains("-")]

In [25]:

clean_fighter_df.to_csv("data/clean_fighter_info.csv")
clean_fighter_df

,name,DOB,ufc_record,weight,reach,stance,height_in
3,Shamil Abdurakhimov,"Sep 02, 1981",20-5-0,235,76,Orthodox,75
5,Daichi Abe,"Nov 27, 1991",6-2-0,170,71,Orthodox,71
8,Klidson Abreu,"Dec 24, 1992",15-4-0 (1 NC),205,74,Orthodox,72
11,Juan Adams,"Jan 16, 1992",5-3-0,265,80,Orthodox,77
12,Anthony Adams,"Jan 13, 1988",8-2-0,185,76,Orthodox,73
...,...,...,...,...,...,...,...
3639,Joao Zeferino,"Jan 15, 1986",21-9-0,170,71,Orthodox,71
3641,Craig Zellner,"Sep 09, 1976",4-3-0,205,74,Orthodox,74
3642,Roman Zentsov,"Sep 10, 1973",18-12-0,230,73,Orthodox,73
3651,James Zikic,"Mar 01, 1977",21-10-2,205,74,Orthodox,74
3652,Errol Zimmerman,"Apr 20, 1986",0-1-0,185,75,Orthodox,75